### PR TITLE
feat: enhance time range selector for metrics - include presets

### LINKED ISSUE #2278: enhance the time range selector for metrics
- [ ] update the start time and end time selector in a single dropdown
- [ ] provide an option of presets ~ last 2 hrs, 4hrs, ...

### PR DESCRIPTION
**Pull request by adarsh0728**
Resolves #2278

### CODE REVIEW

**Comment by adarsh0728** [comment]
We are using  https://mui.com/x/react-date-pickers but for presets (last 1 hr, last 30mins etc) https://mui.com/x/react-date-pickers/shortcuts/ requires pro version (date and time shortcuts). Testing out different libraries and their outputs.

**Comment by adarsh0728** [comment]
Screenshot 2024-12-19 at 1 02 39 PM
Screenshot 2024-12-19 at 1 02 47 PM
Screenshot 2024-12-19 at 1 02 55 PM

**Comment by adarsh0728** [comment]
> Why is the date format so weird?

@whynowy: talking about the attached date format? It's the default format(attached) for date with times. I tried with other formats but didn't work. Will check once more if there's a workaround.
Screenshot 2024-12-19 at 10 43 00 PM
Screenshot 2024-12-19 at 10 43 40 PM

What do you suggest?

**Comment by whynowy** [comment]
> > Why is the date format so weird?
> 
> @whynowy: talking about the attached date format? It's the default format for date with times. I tried with other formats but didn't work. Will check once more if there's a workaround.
> 
> https://mui.com/x/react-date-pickers/date-time-range-field/
> 
> here, it's like `04/17/2022 03:30 PM – 04/21/2022 06:30 PM`
> 
> Screenshot 2024-12-19 at 10 43 00 PM Screenshot 2024-12-19 at 10 43 40 PM
> What do you suggest?

Is it according to different client? What i see in the link you posted is like below.

Screenshot 2024-12-19 at 9 55 19 AM

**Comment by adarsh0728** [comment]
@whynowy: yes it was a different component (for reference i added, but we [aren't using](https://github.com/numaproj/numaflow/pull/2292#issuecomment-2550826853) that). 

I have made the changes and format would be like below. This works?
Screenshot 2024-12-20 at 8 00 44 AM

**Review by whynowy — APPROVED** [review]

**Pull request merged**
