### PR TITLE
fix: podSpec incorrectly configured in case template exist

### LINKED ISSUE #1514: ServiceAccountName incorrectly configured in case vertex template exist
**Describe the bug**

In case the vertex template is configured, the `serviceAccountName` isn't respected and is set to `default`.

**To Reproduce**

A sample pipeline - in this case the `cat` vertice should be configured with serviceAccountName as `test-two` instead of `default`.

```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  templates:
    vertex:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      serviceAccountName: "test-two"
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
```

**Expected behavior**
The serviceAccountName at the vertice level should be adhered

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: v1.29.2
- Numaflow: v1.1.5

**Additional context**

---

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by inishchith**
closes #1514

With this change PodSpec fields are assigned with values from template only if they are null/empty.

### CODE REVIEW

**Review by whynowy — DISMISSED** [review]
LGTM, thanks!

**Comment by inishchith** [comment]
@whynowy - not entirely sure what's breaking. if you could help identify, happy to fix and get this through

**Comment by whynowy** [comment]
> @whynowy - not entirely sure what's breaking. if you could help identify, happy to fix and get this through

Thanks @inishchith ! I will take a look.

**Comment by whynowy** [comment]
> E2e failed because of our recent e2e test image upgrade. It is now fixed after rebasing. cc: @whynowy

:) Thanks @KeranYang

**Review by whynowy — APPROVED** [review]

**Pull request merged**
