### PR TITLE
feat: add server-info support and versioning to MonoVertex

### PR DESCRIPTION
**Pull request by kohlisid**

### CODE REVIEW

**Comment by kohlisid** [comment]
```
2024-08-09T22:17:43.333371Z  INFO Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.2.0-rc4", version: "v0.7.0-rc2", metadata: None }
2024-08-09T22:17:43.333398Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "rustc", platform: "linux/aarch64" }
2024-08-09T22:17:43.333805Z  INFO Server info file /var/run/numaflow/sinker-server-info is not ready, waiting...
2024-08-09T22:17:44.335138Z  INFO Server info file /var/run/numaflow/sinker-server-info is not ready, waiting...
2024-08-09T22:18:06.373836Z  INFO Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.2.0-rc4", version: "v0.7.0-rc2", metadata: None }
2024-08-09T22:18:06.373859Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "rustc", platform: "linux/aarch64" }

```

**Comment by kohlisid** [comment]
Python 
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-c8a2z | grep ServerInfo
2024-08-09T22:29:55.715214Z  INFO Server info file: ServerInfo { protocol: "uds", language: "python", minimum_numaflow_version: "1.2.0-rc4", version: "0.7.3", metadata: Some({}) }

```

**Comment by kohlisid** [comment]
Testing incompatible versions (For testing)
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-qa2bh
2024-08-09T22:50:52.855975Z  INFO Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.2.0-rc4", version: "v0.7.0-rc2", metadata: None }
2024-08-09T22:50:52.855988Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-08-09T22:50:52.856006Z  WARN Error waiting for source server info file: ServerInfoError("SDK version 0.7.0-rc2 must be upgraded to at least 1.7.0-rc2, in order to work with the current numaflow version")
2024-08-09T22:50:52.856009Z ERROR Application error: ForwarderError("Error waiting for server info file")

```

**Comment by kohlisid** [comment]
One good, one bad container with server info
```
2024-08-09T22:59:57.796619Z  INFO Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.2.0-rc4", version: "v0.7.0-rc2", metadata: None }
2024-08-09T22:59:57.796692Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
specifiers: ">=0.7.0-rc2"
sdk_version_semver: Version { major: 0, minor: 7, patch: 0, pre: Prerelease("rc2") }
2024-08-09T22:59:57.796922Z  INFO Server info file: ServerInfo { protocol: "uds", language: "python", minimum_numaflow_version: "1.2.0-rc4", version: "0.7.3", metadata: Some({}) }
2024-08-09T22:59:57.796926Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
specifiers: VersionSpecifier { operator: GreaterThanEqual, version: "1.7.0a1" }
sdk_version_pep440: "0.7.3"
2024-08-09T22:59:57.796938Z  WARN Error waiting for sink server info file: ServerInfoError("SDK version 0.7.3 must be upgraded to at least 1.7.0a1, in order to work with the current numaflow version")
2024-08-09T22:59:57.796941Z ERROR Application error: ForwarderError("Error waiting for server info file")

```

**Comment by kohlisid** [comment]
All green versions
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-8urnj | head -50
2024-08-09T23:09:44.855804Z  INFO Server info file /var/run/numaflow/sourcer-server-info is not ready, waiting...
2024-08-09T23:09:45.856767Z  INFO Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.2.0-rc4", version: "v0.7.0-rc2", metadata: None }
2024-08-09T23:09:45.856802Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
specifiers: ">=0.7.0-rc2"
sdk_version_semver: Version { major: 0, minor: 7, patch: 0, pre: Prerelease("rc2") }
2024-08-09T23:09:45.857192Z  INFO Server info file: ServerInfo { protocol: "uds", language: "python", minimum_numaflow_version: "1.2.0-rc4", version: "0.7.3", metadata: Some({}) }
2024-08-09T23:09:45.857205Z  INFO Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
specifiers: VersionSpecifier { operator: GreaterThanEqual, version: "0.7.0a1" }
sdk_version_pep440: "0.7.3"

```

**Review by vigith — APPROVED** [review]

**Review by yhl25 — APPROVED** [review]
LGTM!

**Pull request merged**
