### PR TITLE
chore: avoid creating kv buckets when watermark is disabled

### PR DESCRIPTION
**Pull request by yhl25**

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Comment by whynowy** [comment]
If watermark is enabled later, will the buckets be created?

**Comment by whynowy** [comment]
And what is the reason we want to skip creating?

**Review by whynowy — CHANGES_REQUESTED** [review]
Please address the concerns.

**Comment by vigith** [comment]
this could cause regressions.

**Pull request closed without merging**
