### PR TITLE
Update examples.md

### PR DESCRIPTION
**Pull request by tasneemkoushar**
Explained the prerequisite step in the Reduce Example page in the doc. 

This PR is for issue #1170

### CODE REVIEW

**Comment by tasneemkoushar** [comment]
@chandankumar4 can you please review this?

**Review by whynowy — CHANGES_REQUESTED** [review]
This is totally wrong.

**Comment by tasneemkoushar** [comment]
Closing this PR, need a little more insight into the problem statement.

**Comment by vigith** [comment]
join our slack channel and you can discuss with @chandankumar4. he can help you.

**Pull request closed without merging**
