### PR TITLE
feat: marshal/unmarshal binary for read message

### PR DESCRIPTION
**Pull request by chromevoid**
TODO:
1. integrate with WAL segment and JetStream
2. performance testing

### CODE REVIEW

**Review by vigith — APPROVED** [review]
can you add a `// TODO` to integrate this with WAL segment and JetStream?

**Comment by whynowy** [comment]
Do we have any data about performance and binary size comparison?

**Comment by whynowy** [comment]
Clicked the wrong button.... reopening...

**Comment by vigith** [comment]
> Do we have any data about performance and binary size comparison?

We will do that once we integrate, we are reprioritizing this ATM.

**Pull request merged**
