### PR TITLE
chore: added Seekr to USERS.md

### PR DESCRIPTION
**Pull request by lanedd**
Added Seekr to the USERS.md file.

### CODE REVIEW

**Comment by whynowy** [comment]
@lanedd - can you address the DCO by signing off your commit? Here is the [reference](https://github.com/numaproj/numaflow/pull/2022/checks?check_run_id=29627137753).

**Comment by lanedd** [comment]
> @lanedd - can you address the DCO by signing off your commit? Here is the [reference](https://github.com/numaproj/numaflow/pull/2022/checks?check_run_id=29627137753).

@whynowy , the DCO check is succesful now.

**Review by vigith — APPROVED** [review]

**Comment by whynowy** [comment]
@lanedd - thanks for raising this PR! Is there anything else you want to add, or it's good to merge?

**Comment by lanedd** [comment]
@whynowy , I think it is good to merge!

**Pull request merged**
