### PR TITLE
feat: use sidecar for ud containers [Breaking k8s < v1.29]

### PR DESCRIPTION
**Pull request by whynowy**
Use [Sidecar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) to run ud containers, to make sure they will be started before and terminated after numa container.

### CODE REVIEW

**Comment by kohlisid** [comment]
@whynowy 
Post this change new versions would not be working with <1.29 right?
Would we want to have a backward compatible version where we enable this with some config etc?
What do you think?

**Comment by whynowy** [comment]
> @whynowy Post this change new versions would not be working with <1.29 right? Would we want to have a backward compatible version where we enable this with some config etc? What do you think?

We don't care if no one uses k8s < 1.29, or anyone uses < 1.29 has a plan to upgrade.

**Review by kohlisid — APPROVED** [review]

**Comment by kohlisid** [comment]
@whynowy 
Please add any container lifecycle timestamps observed for closing this?

**Comment by whynowy** [comment]
> @whynowy Please add any container lifecycle timestamps observed for closing this?

What does this mean?

**Comment by whynowy** [comment]
> @whynowy Please add any container lifecycle timestamps observed for closing this?

```
Init Containers:
  udsource:
    Container ID:   containerd://2b3b0cbc138f053ffe5bd1bbcf5d3a8c285fa88340e3672354a59ca7333f213e
    Image:          quay.io/numaio/numaflow-rs/simple-source:stable
    Image ID:       quay.io/numaio/numaflow-rs/simple-source@sha256:d7960273214db7536d5093d03b23a8bd466867f61ff347839a9ea6e2ac1db4f2
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 19 Nov 2024 17:29:34 -0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:2469/sidecar-livez delay=30s timeout=30s period=60s #success=1 #failure=5
    Environment:
      NUMAFLOW_UD_CONTAINER_TYPE:  udsource
      NUMAFLOW_NAMESPACE:          numaflow-system (v1:metadata.namespace)
      NUMAFLOW_POD:                simple-mono-vertex-mv-0-2g90a (v1:metadata.name)
      NUMAFLOW_REPLICA:             (v1:metadata.annotations['numaflow.numaproj.io/replica'])
      NUMAFLOW_MONO_VERTEX_NAME:   simple-mono-vertex
      NUMAFLOW_CPU_LIMIT:          node allocatable (limits.cpu)
      NUMAFLOW_CPU_REQUEST:        0 (requests.cpu)
      NUMAFLOW_MEMORY_LIMIT:       node allocatable (limits.memory)
      NUMAFLOW_MEMORY_REQUEST:     0 (requests.memory)
    Mounts:
      /var/run/numaflow from var-run-numaflow (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hzwzb (ro)
  transformer:
    Container ID:   containerd://92cd9e3b5a9ff149d339e78606b674215ecb0f931f9f2e0cf65cd00340c924b7
    Image:          quay.io/numaio/numaflow-rs/source-transformer-now:stable
    Image ID:       quay.io/numaio/numaflow-rs/source-transformer-now@sha256:843a9cafb67eaeadb6468bf9bf7225b43b30c648d41b87222fb2a9ea8d2ffcd9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 19 Nov 2024 17:29:35 -0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:2469/sidecar-livez delay=30s timeout=30s period=60s #success=1 #failure=5
    Environment:
      NUMAFLOW_UD_CONTAINER_TYPE:  transformer
      NUMAFLOW_NAMESPACE:          numaflow-system (v1:metadata.namespace)
      NUMAFLOW_POD:                simple-mono-vertex-mv-0-2g90a (v1:metadata.name)
      NUMAFLOW_REPLICA:             (v1:metadata.annotations['numaflow.numaproj.io/replica'])
      NUMAFLOW_MONO_VERTEX_NAME:   simple-mono-vertex
      NUMAFLOW_CPU_LIMIT:          node allocatable (limits.cpu)
      NUMAFLOW_CPU_REQUEST:        0 (requests.cpu)
      NUMAFLOW_MEMORY_LIMIT:       node allocatable (limits.memory)
      NUMAFLOW_MEMORY_REQUEST:     0 (requests.memory)
    Mounts:
      /var/run/numaflow from var-run-numaflow (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hzwzb (ro)
  udsink:
    Container ID:   containerd://9a047a26c1bb12ca88eb825dbcd20673bb3988a62adbb77d668758968733aa57
    Image:          quay.io/numaio/numaflow-rs/sink-log:stable
    Image ID:       quay.io/numaio/numaflow-rs/sink-log@sha256:e6627f22b03152f5546d1d36ab7a01de2d39bb6f9d5fa2afd53b96b7f0fe0815
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 19 Nov 2024 17:29:36 -0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:2469/sidecar-livez delay=30s timeout=30s period=60s #success=1 #failure=5
    Environment:
      NUMAFLOW_UD_CONTAINER_TYPE:  udsink
      NUMAFLOW_NAMESPACE:          numaflow-system (v1:metadata.namespace)
      NUMAFLOW_POD:                simple-mono-vertex-mv-0-2g90a (v1:metadata.name)
      NUMAFLOW_REPLICA:             (v1:metadata.annotations['numaflow.numaproj.io/replica'])
      NUMAFLOW_MONO_VERTEX_NAME:   simple-mono-vertex
      NUMAFLOW_CPU_LIMIT:          node allocatable (limits.cpu)
      NUMAFLOW_CPU_REQUEST:        0 (requests.cpu)
      NUMAFLOW_MEMORY_LIMIT:       node allocatable (limits.memory)
      NUMAFLOW_MEMORY_REQUEST:     0 (requests.memory)
    Mounts:
      /var/run/numaflow from var-run-numaflow (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hzwzb (ro)
Containers:
  numa:
    Container ID:  containerd://7934dff671f3609c79249880ad7eca9d508d5ab14aafbc302bd640a6a444e347
    Image:         quay.io/numaproj/numaflow:latest
    Image ID:      sha256:bbb682c0fb7a106919432d6a50acd9e1e77e84f26fbab5f1084d87df4776e88d
    Port:          2469/TCP
    Host Port:     0/TCP
    Command:
      /bin/numaflow-rs
    Args:
      --rust
    State:          Running
      Started:      Tue, 19 Nov 2024 17:29:37 -0800
    Ready:          True
    Restart Count:  0
```

**Comment by kohlisid** [comment]
@whynowy Thank you :D

**Review by KeranYang — APPROVED** [review]

**Review by vigith — APPROVED** [review]

**Pull request merged**
