### PR TITLE
fix: update SDKs to stable image

### LINKED ISSUE #1745: Quickstart even-odd pipeline does not deploy
**Describe the bug**
As we were following the steps on the quiclstart we get to the following step: 

`kubectl apply -f https://raw.githubusercontent.com/numaproj/numaflow/main/examples/2-even-odd-pipeline.yaml`

after you run this if you run `kubectl get pods`. You will find that in the even odd utf vertex you will get the following error: 

```
"Failed to pull image "quay.io/numaio/numaflow-go/map-even-odd:v0.7.0": Error response from daemon: manifest for quay.io/numaio/numaflow-go/map-even-odd:v0.7.0 not found: manifest unknown: manifest unknown"
```

**To Reproduce**

follow the quick start guide and once you deploy the following commands you will see the error
1. `kubectl apply -f https://raw.githubusercontent.com/numaproj/numaflow/main/examples/2-even-odd-pipeline.yaml`
2. `kubectl get pods`

**Expected behavior**
all the pods must have running status

**Screenshots**

Screenshot 2024-05-30 at 12 22 19 PM

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

### PR DESCRIPTION
**Pull request by samhith-kakarla**
fixes #1745 
Screenshot 2024-05-30 at 12 43 48 PM

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Review by kohlisid — APPROVED** [review]

**Review by KeranYang — CHANGES_REQUESTED** [review]
Can we also update other examples too? As long as we have the stable tag available for that image, we should use stable. Thanks!

**Comment by samhith-kakarla** [comment]
I will take a look at the other examples too

**Comment by samhith-kakarla** [comment]
Screenshot 2024-05-31 at 3 54 28 PM


all but the kafka-in pod is running due to a broker error, which is expected: `"level":"info","ts":"2024-05-31T22:31:14.99192722Z","logger":"numaflow.Source-processor","caller":"sarama@v1.43.0/broker.go:205","msg":"Failed to connect to broker my-broker1:19700: dial tcp: lookup my-broker1 on 10.96.0.10:53: no such host","pipeline":"join-on-reduce","vertex":"kafka-in"`

**Review by KeranYang — APPROVED** [review]

**Comment by KeranYang** [comment]
Thank you! @samhith-kakarla

**Pull request merged**
