### PR TITLE
fix(docs): fix a typo

### PR DESCRIPTION
**Pull request by si3nloong**
Signed-off-by: @si3nloong  [sianloong90@gmail.com](mailto:sianloong90@gmail.com)

Fix typos in documentation.

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Comment by vigith** [comment]
could you please sign your commit?

**Comment by si3nloong** [comment]
> could you please sign your commit?

Done.

**Comment by vigith** [comment]
DCO is still failing.

**Comment by si3nloong** [comment]
> DCO is still failing.

check again, I saw it passed

**Pull request merged**
