### PR TITLE
feat:KafkaSource supports KafkaVersion modification

### PR DESCRIPTION
**Pull request by qianbeibuzui**
KafkaSource supports KafkaVersion modification.

But I am not very familiar with the packaging process of this project, and I may need you to repackage and execute the make codegen of makefle.

### CODE REVIEW

**Comment by vigith** [comment]
thank you @qianbeibuzui for the contribution. Could you please make the DCO pass?

**Comment by vigith** [comment]
just run `make codegen`, it should do the trick.

**Comment by vigith** [comment]
you do not have to manually change any rust code in `numaflow-models`, it is generated automatically when codegen is run.

**Comment by qianbeibuzui** [comment]
> 您不必手动更改任何 rust 代码`numaflow-models`，它会在运行 codegen 时自动生成。

是的，我重新看了该文件发现了“Code generated by Openapi Generator. DO NOT EDIT.”

**Comment by vigith** [comment]
do you mind sharing the output of `make codegen`? I would like to find out what is causing this problem.

**Comment by qianbeibuzui** [comment]
> 你介意分享一下 的输出吗`make codegen`？我想找出导致这个问题的原因。

image

**Comment by whynowy** [comment]
@qianbeibuzui - I understand you have some trouble on `make codegen`. If you don't mind, can you please revert those `codegen` related changes, we will help you on it and raise a PR to your branch.

**Comment by qianbeibuzui** [comment]
> @qianbeibuzui- 我了解您在 上遇到了一些麻烦`make codegen`。如果您不介意的话，您能否还原那些`codegen`相关更改，我们将为您提供帮助并向您的分支提交 PR。

As you said, I have restored the code generated by codegen. Please assist me in building codegen.

**Comment by vigith** [comment]
please merge https://github.com/qianbeibuzui/numaflow/pull/1

**Review by vigith — APPROVED** [review]

**Comment by syayi** [comment]
@qianbeibuzui Thank you for contributing to Numaflow. Sorry to comment this ask on the PR. Do you mind sharing how you learnt about Numaflow project and any specific use case you're planning to use for?

**Comment by qianbeibuzui** [comment]
> @qianbeibuzui感谢您对 Numaflow 的贡献。很抱歉在 PR 上评论此问题。您介意分享一下您是如何了解 Numaflow 项目的，以及您计划使用的任何具体用例吗？

Nice to discuss this issue with you, but my English is not very good, please don't laugh.
How did you come into contact with the Numaflow project?
I need to use a "real-time streaming data processing framework" for work, and initially I chose to use Flink as my first choice., But my colleagues' main technical stacks are Python and Golang.
Due to its focus on Java, Flink is not as friendly to other development languages.
Finally, by searching for relevant information: (found numaflow, benthos on Reddit)
2. Specific use cases planned for use?
As mentioned above, for data stream processing and machine learning,
Example: Synchronize MySQL data to startrocks and clickhouse, and process the data
Example: Data transfer to Python for machine learning
Finally, please add:
I think numaflow is a great direction in the field of real-time data stream processing.
Looking forward to numaflow being as excellent as Argo.

**Comment by syayi** [comment]
No worries and thanks a lot @qianbeibuzui for sharing the information, really great to know the reason, the use cases and that you appreciate the project. We are always happy to connect with our community to gather feedback and improve.

Also, we’ve seen more Numaflow users adding themselves to the USERS list. It’d be great to have you as well, would you be open to it? It helps community discover different use cases and gives Numaflow a bit more visibility too.

https://github.com/numaproj/numaflow/blob/main/USERS.md

**Comment by qianbeibuzui** [comment]
> 不用担心，非常感谢@qianbeibuzui分享信息，很高兴知道原因、用例以及您对项目的赞赏。我们总是乐于与社区联系，收集反馈并改进。
> 
> 此外，我们看到越来越多的 Numaflow 用户将自己添加到用户列表中。如果您也加入就太好了，您愿意吗？它可以帮助社区发现不同的用例，也让 Numaflow 更具可见性。
> 
> https://github.com/numaproj/numaflow/blob/main/USERS.md

I will definitely write it down after my project is completed

**Pull request merged**
