### PR TITLE
chore: add missed tests for java

### PR DESCRIPTION
**Pull request by KeranYang**
Explain what this PR does.

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Comment by kohlisid** [comment]
Thanks @KeranYang :D
E2E are really important for us. But do you have any plans to tackle the flaky bits?

**Comment by KeranYang** [comment]
Yes! @kohlisid thanks for raising this. I have been working on several flaky e2e tests since I joined the team. Just got a bit lazy recently lol. I will take a look at the current ones soon(some time next week).

**Comment by kohlisid** [comment]
@KeranYang You're the senpai 🙌

**Comment by kohlisid** [comment]
Let me know if I can be of any help :D

**Pull request merged**
