### PR TITLE
docs: update to add join vertex and v0.10 changes

### LINKED ISSUE #1071: improve JOIN vertex doc
Add more documentation to [JOIN vertex](https://numaflow.numaproj.io/user-guide/reference/join-vertex/) from the [blog](https://blog.numaproj.io/from-trees-to-directed-graphs-4e59f0463cfc).

### PR DESCRIPTION
**Pull request by VishalSoni07**
Fixes #1071

Explain what this PR does.
As part of Hactoberfest 2023 we are fixing the issue: https://github.com/numaproj/numaflow/issues/1071 to improve Documentation for Join-Vertex. Referring from this [blog](https://blog.numaproj.io/from-trees-to-directed-graphs-4e59f0463cfc) added more relevant information around Join Vertex and the latest changes as part of v0.10 update.

### CODE REVIEW

**Comment by vigith** [comment]
could please make the DCO pass?

**Review by vigith — COMMENTED** [review]
thank you @VishalSoni07, there are duplicates the whole section repeats itself, could you please remove the duplicates?

**Comment by VishalSoni07** [comment]
> thank you @VishalSoni07, there are duplicates the whole section repeats itself, could you please remove the duplicates?

Thanks, @vigith. I have updated the document to remove duplicate sections.

**Review by vigith — COMMENTED** [review]
please fix the DCO too :)

**Comment by vigith** [comment]
also, could you please move `Cycles` to before `Next Steps` ?

**Comment by VishalSoni07** [comment]
> please fix the DCO too :)

Sure, just did :)

**Comment by VishalSoni07** [comment]
> also, could you please move `Cycles` to before `Next Steps` ?

Sure, done :)

**Comment by VishalSoni07** [comment]
@vigith, can you please also add **hactoberfest** label to this PR?

**Review by vigith — APPROVED** [review]
Thank you for your contribution 🎉

**Comment by VishalSoni07** [comment]
> Thank you for your contribution 🎉

Thanks to you for the help and review.

**Pull request merged**
