### PR TITLE
Changed all errors logs in redis isb to debug logs

### PR DESCRIPTION
**Pull request by Krithika3**
Please explain what this PR does?

### CODE REVIEW

**Comment by vigith** [comment]
there are still many log entries in the log, we might have to tackle this differently

**Review by vigith — COMMENTED** [review]
i think we shouldn't mask `error` as `debug`.. we might have to change the test log level perhaps?

**Comment by Krithika3** [comment]
> i think we shouldn't mask `error` as `debug`.. we might have to change the test log level perhaps?

I think if we have them as error logs, even the lowest log level will display them if I am not mistaken?

**Comment by Krithika3** [comment]
I think another reason for so many logs in the test is also the refreshInterval that we set. Let me take a look at that.

**Comment by vigith** [comment]
> > i think we shouldn't mask `error` as `debug`.. we might have to change the test log level perhaps?
> 
> I think if we have them as error logs, even the lowest log level will display them if I am not mistaken?

Setting log level to fatal is one option, so only fatal and above will be printed.

**Comment by whynowy** [comment]
> > > i think we shouldn't mask `error` as `debug`.. we might have to change the test log level perhaps?
> > 
> > 
> > I think if we have them as error logs, even the lowest log level will display them if I am not mistaken?
> 
> Setting log level to fatal is one option, so only fatal and above will be printed.

No.. no, `Fatal` exits the application.

**Comment by vigith** [comment]
> > > > i think we shouldn't mask `error` as `debug`.. we might have to change the test log level perhaps?
> > > 
> > > 
> > > I think if we have them as error logs, even the lowest log level will display them if I am not mistaken?
> > 
> > 
> > Setting log level to fatal is one option, so only fatal and above will be printed.
> 
> No.. no, `Fatal` exits the application.

this is just for test log.level

**Comment by whynowy** [comment]
Why logrus is needed?

**Comment by Krithika3** [comment]
> Why logrus is needed?

I think we can use zap

**Comment by Krithika3** [comment]
the watermark test failed again. What is the way around this?

**Comment by vigith** [comment]
> the watermark test failed again. What is the way around this or how do we fix it?

I don't think it is the watermark test that failed, but rather

```
# github.com/numaproj/numaflow/pkg/isb/redis [github.com/numaproj/numaflow/pkg/isb/redis.test]
Error: pkg/isb/redis/read_test.go:36:2: undefined: log
Error: pkg/isb/redis/read_test.go:68:2: undefined: log
Error: pkg/isb/redis/read_test.go:166:2: undefined: log
Error: pkg/isb/redis/read_test.go:289:2: undefined: log
```

**Comment by Krithika3** [comment]
> > the watermark test failed again. What is the way around this or how do we fix it?
> 
> I don't think it is the watermark test that failed, but rather
> 
> ```
> # github.com/numaproj/numaflow/pkg/isb/redis [github.com/numaproj/numaflow/pkg/isb/redis.test]
> Error: pkg/isb/redis/read_test.go:36:2: undefined: log
> Error: pkg/isb/redis/read_test.go:68:2: undefined: log
> Error: pkg/isb/redis/read_test.go:166:2: undefined: log
> Error: pkg/isb/redis/read_test.go:289:2: undefined: log
> ```

Ah ok,thanks

**Comment by Krithika3** [comment]
I closed this as this is not the right way to do this. I will open a new PR with the changes

**Pull request closed without merging**
