### PR TITLE
fix: allow late message as long as window is not closed

### PR DESCRIPTION
**Pull request by vigith**
Even if a message is late, we can push it in as long as the window is open.

### CODE REVIEW

**Review by chromevoid — APPROVED** [review]

**Comment by whynowy** [comment]
How come later message comes earlier than the watermark? I remember we discussed before, that the late message is always later than the wartermark.

**Comment by chromevoid** [comment]
> How come late message comes earlier than the watermark? I remember we discussed before, that the late message is always later than the wartermark.

context is https://github.com/numaproj/numaflow/issues/697 
we'd like to add latency to COB.

**Comment by vigith** [comment]
> How come late message comes earlier than the watermark? I remember we discussed before, that the late message is always later than the wartermark.

Watermark and lateness gets decoupled at source, so it is totally possible that an element with isLate field set to true reach Vn vertex  before the watermark which caused it to late has arrived the same vertex.

**Comment by whynowy** [comment]
> > How come late message comes earlier than the watermark? I remember we discussed before, that the late message is always later than the wartermark.
> 
> context is #697 we'd like to add latency to COB, so the late message could come earlier than the `watermark minus latency` time.
> 
> This PR is the preparation for the above task.



> > How come late message comes earlier than the watermark? I remember we discussed before, that the late message is always later than the wartermark.
> 
> Watermark and lateness get decoupled at the source, so it is totally possible that an element with isLate field set to true reaches Vn vertex before the watermark, which caused it to be late, has arrived at the same vertex.

Even without the context https://github.com/numaproj/numaflow/issues/697? I remember we discussed before about this, you said that was impossible :)

**Comment by vigith** [comment]
> Even without the context #697? I remember we discussed before about this, you said that was impossible :)


lol, maybe I had got the question wrong earlier 😁. But, it does make sense right?

**Comment by whynowy** [comment]
> > Even without the context #697? I remember we discussed before about this, you said that was impossible :)
> 
> lol, maybe I had got the question wrong earlier 😁. But, it does make sense right?

On the other hand, if this is possible, then a "good" data can also come later than the wartermark, if that's the case, is our watermark propagation still trustable?

**Comment by vigith** [comment]
> On the other hand, if this is possible, then a "good" data can also come later than the wartermark, if that's the case, is our watermark propagation still trustable?

The above condition will never happen. I think there is a confusion. There a no watermark propagation problem. Watermark will always trail behind the data. This is the expected behavior.

**Review by whynowy — APPROVED** [review]

**Comment by ashwinidulams** [comment]
only thought is that the same event stream may or may not drop the late events for subsequent runs with the same data set. Since the condition of watermark trailing late events is arbitrary and is not guaranteed always.

**Comment by ashwinidulams** [comment]
> only thought is that the same event stream may or may not drop the late events for subsequent runs with the same data set. Since the condition of watermark trailing late events is arbitrary and is not guaranteed always.

however, i think this is ok as there is no determinism in watermark progression and is totally dependent on how the previous vertices go about processing the data stream.

**Review by ashwinidulams — APPROVED** [review]

**Review by yhl25 — APPROVED** [review]

**Comment by vigith** [comment]
When we tackle #697 we will introduce a flag to make this optional. There could be a case where user does not want late data to be processed.

**Pull request merged**
